apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyhrtsg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyhrtsg
  template:
    metadata:
      labels:
        app: tyhrtsg
    spec:
      containers:
      - image: okteto.dev/tyhrtsg:latest
        name: tyhrtsg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7633839a-0154-4ef2-aa0d-7dc7aa372973"
        - name: Vless_Path
          value: "/jkdregegbse7"
        - name: Vmess_UUID
          value: "7633839a-0154-4ef2-aa0d-7dc7aa372973"
        - name: Vmess_Path
          value: "/uiytyjhgnd"
        - name: Share_Path
          value: "/v2link"
